# Generated by Django 4.1.5 on 2023-01-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Values",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("values", models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name="Person",
        ),
    ]
