# Generated by Django 4.1.5 on 2023-01-26 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viz", "0002_values_delete_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="values",
            name="values",
        ),
        migrations.AddField(
            model_name="values",
            name="valueList",
            field=models.TextField(null=True),
        ),
    ]
